puts "====== Print simple text ========="
print "Hello world!!!"
print "\n"
print "Hello baby! \nI miss you!!"
print "\n"
print "Fullname \t\t Birthday \t\t Address\n"
print "Lung Thi Linh \t 01/02/2000 \t Ha Noi\n"
print "Tran Van Gi \t 05/12/1999 \t Nam Dinh\n"
puts "========================================="
puts ""